import { session } from "@/utils/utils";
export default [
    {
        path: "guanzhong/add",
        name: "IndexguanzhongAdd",
        component: () => import("@/views/guanzhong/add-web.vue"),
        meta: { title: "观众添加" },
    },
    {
        path: "pinglun/add",
        name: "IndexpinglunAdd",
        component: () => import("@/views/pinglun/add-web.vue"),
        meta: { title: "评论添加", authLogin: true, msg: true },
    },
    {
        path: "pinglunhuifu/add",
        name: "IndexpinglunhuifuAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/pinglunhuifu/add-web.vue"),
        meta: { title: "评论回复添加", authLogin: true, msg: true },
    },
    {
        path: "dianzan/add",
        name: "IndexdianzanAdd",
        component: () => import("@/views/dianzan/add-web.vue"),
        meta: { title: "点赞添加", authLogin: true, msg: true },
    },
    {
        path: "jiaolian",
        name: "IndexjiaolianList",
        component: () => import("@/views/jiaolian/index.vue"),
        meta: { title: "教练列表" },
    },
    {
        path: "jiaolian/detail",
        name: "IndexjiaolianDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jiaolian/detail-web.vue"),
        meta: { title: "教练详情" },
    },
    {
        path: "xinwengonggao",
        name: "IndexxinwengonggaoList",
        component: () => import("@/views/xinwengonggao/index.vue"),
        meta: { title: "新闻公告列表" },
    },
    {
        path: "xinwengonggao/detail",
        name: "IndexxinwengonggaoDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/xinwengonggao/detail-web.vue"),
        meta: { title: "新闻公告详情" },
    },
    {
        path: "qiudui",
        name: "IndexqiuduiList",
        component: () => import("@/views/qiudui/index.vue"),
        meta: { title: "球队列表" },
    },
    {
        path: "qiudui/detail",
        name: "IndexqiuduiDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/qiudui/detail-web.vue"),
        meta: { title: "球队详情" },
    },
    {
        path: "bisaixinxi",
        name: "IndexbisaixinxiList",
        component: () => import("@/views/bisaixinxi/index.vue"),
        meta: { title: "比赛信息列表" },
    },
    {
        path: "bisaixinxi/detail",
        name: "IndexbisaixinxiDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/bisaixinxi/detail-web.vue"),
        meta: { title: "比赛信息详情" },
    },
    {
        path: "bisaibaoming/add",
        name: "IndexbisaibaomingAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/bisaibaoming/add-web.vue"),
        meta: { title: "比赛报名添加", authLogin: true, msg: true },
    },
    {
        path: "saichengbiao/detail",
        name: "IndexsaichengbiaoDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/saichengbiao/detail-web.vue"),
        meta: { title: "赛程表详情" },
    },
];
